### ISSUE TITLE
build failed with linker error

### ISSUE THREAD

**Issue by bfrk** [ChimeraTK/ControlSystemAdapter#1]
I was trying to build the project. As there is no README or INSTALL or any other information about how to build, I reverted to guessing. So I did it like this:

`franksen@tiber: /tmp/ControlSystemAdapter > cmake CMakeLists.txt`
(this failed at first but I was just missing some boost libs)

Now did make:

```
franksen@tiber: /tmp/ControlSystemAdapter > make
[ 42%] Built target ControlSystemAdapter
[ 50%] Built target fullStubTest
[ 57%] Built target testControlSystemSynchronizationUtility
[ 64%] Built target testDeviceSynchronizationUtility
[ 71%] Built target testPVManager
Scanning dependencies of target testProcessArray
[ 78%] Building CXX object CMakeFiles/testProcessArray.dir/tests/src/testProcessArray.cpp.o
Linking CXX executable testProcessArray
CMakeFiles/testProcessArray.dir/tests/src/testProcessArray.cpp.o: In function `mtca4u::ProcessArrayTest<unsigned int>::testSwap()':
testProcessArray.cpp:(.text._ZN6mtca4u16ProcessArrayTestIjE8testSwapEv[_ZN6mtca4u16ProcessArrayTestIjE8testSwapEv]+0x92): undefined reference to `mtca4u::ProcessArrayTest<unsigned int>::SOME_NUMBER'
CMakeFiles/testProcessArray.dir/tests/src/testProcessArray.cpp.o: In function `mtca4u::ProcessArrayTest<unsigned int>::testSynchronization()':
testProcessArray.cpp:(.text._ZN6mtca4u16ProcessArrayTestIjE19testSynchronizationEv[_ZN6mtca4u16ProcessArrayTestIjE19testSynchronizationEv]+0xff): undefined reference to `mtca4u::ProcessArrayTest<unsigned int>::SOME_NUMBER'
collect2: error: ld returned 1 exit status
make[2]: *** [testProcessArray] Error 1
make[1]: *** [CMakeFiles/testProcessArray.dir/all] Error 2
make: *** [all] Error 2
```

FYI:

```
franksen@tiber: /tmp/ControlSystemAdapter > cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
franksen@tiber: /tmp/ControlSystemAdapter > gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
franksen@tiber: /tmp/ControlSystemAdapter > ld --version
GNU ld (GNU Binutils for Ubuntu) 2.24
```

**Comment by killenb** [comment]
You are trying to do a so called "in source build", which means you are executing cmake in the source directory where the CMakeLists.txt is located. This currently is not supported, and usually discouraged because it clutters the source code with the build files and complicates version control.

The solution is to do an "out of source build". You create a build directory and run cmake from there, pointing to the directory with the source code.
/tmp > mkdir ControlSystemAdapter_build; cd ControlSystemAdapter_build
/tmp/ControlSystemAdapter_build > cmake ../ControlSystemAdapter
/tmp/ControlSystemAdapter_build > make

This should work. Please let us know if you still have problems.

Thanks for the feedback. We will add this information to the documentation.

**Comment by bfrk** [comment]
I did as you suggested but get the same error as before:

```
[...]
CMakeFiles/testProcessArray.dir/tests/src/testProcessArray.cpp.o: In function `mtca4u::ProcessArrayTest<unsigned int>::testSwap()':
testProcessArray.cpp:(.text._ZN6mtca4u16ProcessArrayTestIjE8testSwapEv[_ZN6mtca4u16ProcessArrayTestIjE8testSwapEv]+0x92): undefined reference to `mtca4u::ProcessArrayTest<unsigned int>::SOME_NUMBER'
CMakeFiles/testProcessArray.dir/tests/src/testProcessArray.cpp.o: In function `mtca4u::ProcessArrayTest<unsigned int>::testSynchronization()':
testProcessArray.cpp:(.text._ZN6mtca4u16ProcessArrayTestIjE19testSynchronizationEv[_ZN6mtca4u16ProcessArrayTestIjE19testSynchronizationEv]+0xff): undefined reference to `mtca4u::ProcessArrayTest<unsigned int>::SOME_NUMBER'
collect2: error: ld returned 1 exit status
```

**Comment by killenb** [comment]
Ah, sorry I forgot to mention: If you once tried an "in source build", and then run cmake from another directory and point it to that source, cmake will not reconfigure but pick up the "in source build" configuration. So you first have to clean up the source code directory.

You can either do a "git status", revert all modified files and remove all untracked files, or you can simply delete the source code directory and do a fresh checkout.

Also the build directory has to be empty when you run cmake for the first time, so you have to clean up the files from the failed, previous attempt.

**Comment by bfrk** [comment]
This what I did, sorry forgot to mention it (`git clean -f -d` etc).

BTW, It builds fine when I #define SOME_NUMBER as 42 instead of using a static const member:

```
diff --git a/tests/src/testProcessArray.cpp b/tests/src/testProcessArray.cpp
index 27afeb2..c56feed 100644
--- a/tests/src/testProcessArray.cpp
+++ b/tests/src/testProcessArray.cpp
@@ -30,10 +30,11 @@ namespace mtca4u {
 
   private:
     static size_t const N_ELEMENTS = 12;
-    static size_t const SOME_NUMBER = 42; // just some number to add so the content if not equal to the index
 
   };
 
+#define SOME_NUMBER 42
+
   /**
    * The boost test suite which executes the ProcessArrayTest.
    */
```

**Comment by killenb** [comment]
Sorry for the slow reply. I would like to understand why it is not working for you, but somehow I cannot reproduce you problem. Did you use some special CMake flags?

I could compile without problems on Ubuntu 14.4 and 16.4. I also tried clang on both distributions, which also worked and compiled without warning.

BTW: The in-source build was definitely not causing the problem. I had a modified file which caused my build to fail, which I reverted when I cleaned up the cmake files. The in-source build works fine for me as well.

Could you please try if replacing 'static size_t const' with 'static constexpr size_t' works for you?

`diff --git a/tests/src/testProcessArray.cpp b/tests/src/testProcessArray.cpp
index 27afeb2..f70e88b 100644
--- a/tests/src/testProcessArray.cpp
+++ b/tests/src/testProcessArray.cpp
@@ -29,8 +29,8 @@ namespace mtca4u {
     static void testSynchronization();
 
   private:
-    static size_t const N_ELEMENTS = 12;
-    static size_t const SOME_NUMBER = 42; // just some number to add so the content if not equal to the index
+    static constexpr size_t N_ELEMENTS = 12;
+    static constexpr size_t SOME_NUMBER = 42; // just some number to add so the content if not equal to the index
 
   };
`

**Comment by bfrk** [comment]
Long delay here, too, no problem :)

Unfortunately, using 'constexpr' in the manner you indicated above does not help. Perhaps this is a bug in the 32-bit version of gcc-4.8?

BTW, I would like see the exact command line arguments when make invokes gcc or the linker. How can I achieve this?

**Comment by bfrk** [comment]
Hmm, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=45082 seems to suggest that your code is at fault, not the compiler.

**Comment by smarsching** [comment]
I agree that this is indeed a problem in the code, not the compiler.
Stroustrups's "The C++ Programming Language, 4th Edition" says on page 506: "[I]t is possible to initialize a static member in the class declaration. [...] If (and only if) you use an initialized member in a way that requires it to be stored as an object in memory, the member must be (uniquely) defined somewhere. The initializer may not be repeated."

Creating a reference to the static constant clearly constitutes such a case. The book mentiones creating a pointer to constant as an example, but as references internally work like pointers, this clearly applies to references, too.

If yo think about it, it actually makes sense: In order to pass something as a pointer or reference, you need an address, where it is stored. Without an explicit definition of the constant, the compiler would only have two choices: Create an implicit definition where the constant is used (e.g. the point in the code where it is passed as a reference) or creating an implicit definition with static linkage for each compilation unit where it is used. The first option could have unexpected results regarding the validity of the reference and the second one would increase memory usage due to multiple copies needing to be present permanently.

The best solution would be to supply a definition outside the class definition, while keeping the declaration and initialization inside the class definition. However, this is tricky due to the fact that ProcessArrayTest is a class template. For this reason, I chose the simpler solution of making SOME_NUMBER a static constant outside the class definition. As we only use it locally in the file and it does not depend on the template parameter, this should be fine.

57d6f6a9e86aad36f2b92402c275489caf619689 should fix this problem. Unfortunately, I cannot test this because my compiler did not complain in the first place.

@bfrk Could you please give the updated code a try?

**Comment by killenb** [comment]
> BTW, I would like see the exact command line arguments when make invokes gcc or the linker. How can I achieve this?

With Makefiles generated by CMake you can use
`make VERBOSE=1`

**Comment by bfrk** [comment]
Yes, builds fine now. Thanks!
