### ISSUE TITLE
Include error

### ISSUE THREAD

**Issue by jmrahm** [ChimeraTK/ControlSystemAdapter#7]
Hello, I get an include file error during build process.

> In file included from ChimeraTK-ControlSystemAdapter/tests/src/testReferenceTestCoreWithTread.cpp:6:0:
ChimeraTK-ControlSystemAdapter/tests/include/ChimeraTK/ControlSystemAdapter/Testing/IndependentTestCore.h:7:58: fatal error: ChimeraTK/ControlSystemAdapter/ProcessScalar.h: No such file or directory

Maybe there is a missing include_directories in cmake file?
Best regards

**Comment by mhier** [comment]
There no longer is a ProcessScalar.h include file, the ProcessArray.h should be included instead. This should now be fixed in the master. (In our continuous integration test environment the old header file was still present in the installation directory and obviously taken from there, until the automatic clean happened this night...)
