### ISSUE TITLE
Test missing for std::string data type

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ControlSystemAdapter#9]
There seem to be no test for the std::string data type. At least the just-fixed bug about the wrong default argument for the scalar initial value in DevicePVManager::createProcessArray is not covered.

**Comment by killenb** [comment]
Solved in 5c5527ced3240df604c522502a5b3307d6273479
All places where the supported data types are tested have been extended with std::string and (u)int64_t.

It turned out that std::string was not working for the TypeChangingDecorator as user type. This has been fixed as well.

The tests for the ReferenceTestApplication (fullStubTest) has also been extended with strings. In this course strings have been added to the ReferenceTestApplication, which also solves #15
